# Check `man 5 alacritty` for the reference

[env]
WINIT_X11_SCALE_FACTOR = "1"

[window]
padding = { x = 5, y = 5 }
opacity = 0.9

[font]
size = 10.0

# Gruvbox dark
[colors]

  # Default colors
  [colors.primary]
  # hard contrast background = = '#1d2021'
  background = '#282828'
  # soft contrast background = = '#32302f'
  foreground = '#ebdbb2'

  # Normal colors
  [colors.normal]
  black   = '#282828'
  red     = '#cc241d'
  green   = '#98971a'
  yellow  = '#d79921'
  blue    = '#458588'
  magenta = '#b16286'
  cyan    = '#689d6a'
  white   = '#a89984'

  # Bright colors
  [colors.bright]
  black   = '#928374'
  red     = '#fb4934'
  green   = '#b8bb26'
  yellow  = '#fabd2f'
  blue    = '#83a598'
  magenta = '#d3869b'
  cyan    = '#8ec07c'
  white   = '#ebdbb2'

[keyboard]
bindings = [
  { key = "C",        mods = "Alt",           action = "Copy" },
  { key = "V",        mods = "Alt",           action = "Paste" },
  { key = "U",        mods = "Alt",           action = "ScrollPageUp" },
  { key = "D",        mods = "Alt",           action = "ScrollPageDown" },
  { key = "K",        mods = "Alt",           action = "ScrollLineUp" },
  { key = "J",        mods = "Alt",           action = "ScrollLineDown" },
  { key = "G",        mods = "Alt",           action = "ScrollToTop" },
  { key = "G",        mods = "Alt|Shift",     action = "ScrollToBottom" },
  { key = "K",        mods = "Alt|Shift",     action = "IncreaseFontSize" },
  { key = "J",        mods = "Alt|Shift",     action = "DecreaseFontSize" },
  { key = "Slash",    mods = "Control",       action = "SpawnNewInstance" },
  { key = "5",        mods = "Shift",         mode = "Vi", action = "Last" },
  { key = "6",        mods = "Shift",         mode = "Vi", action = "Bracket" },
  { key = "7",        mods = "Shift",         mode = "Vi", action = "FirstOccupied" },
]
