# Configuration for Alacritty, the GPU enhanced terminal emulator
# Check /usr/share/examples/alacritty/alacritty.yml for the reference

env:
  WINIT_X11_SCALE_FACTOR: "1"

window:
  padding:
    x: 5
    y: 5

  title: Alacritty

  class:
    instance: Alacritty
    general: Alacritty

  history: 10000

  dynamic_title: true

# background_opacity: 0.9

font:
  size: 10.0

  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  offset:
    x: 0
    y: 0

# Colors (Gruvbox dark)
colors:
  primary:
    # hard contrast: background = '#1d2021'
    background: '#282828'
    # soft contrast: background = '#32302f'
    foreground: '#ebdbb2'

  normal:
    black:   '#282828'
    red:     '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#689d6a'
    white:   '#a89984'

  bright:
    black:   '#928374'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#8ec07c'
    white:   '#ebdbb2'

key_bindings:
  - { key: C,        mods: Alt,           action: Copy             }
  - { key: V,        mods: Alt,           action: Paste            }
  - { key: U,        mods: Alt,           action: ScrollPageUp     }
  - { key: D,        mods: Alt,           action: ScrollPageDown   }
  - { key: K,        mods: Alt,           action: ScrollLineUp     }
  - { key: J,        mods: Alt,           action: ScrollLineDown   }
  - { key: G,        mods: Alt,           action: ScrollToTop      }
  - { key: G,        mods: Alt|Shift,     action: ScrollToBottom   }
  - { key: K,        mods: Alt|Shift,     action: IncreaseFontSize }
  - { key: J,        mods: Alt|Shift,     action: DecreaseFontSize }
  - { key: Slash,    mods: Control,       action: SpawnNewInstance }
  - { key: 05,       mods: Shift,         mode: Vi, action: Last   }
  - { key: 06,       mods: Shift,         mode: Vi, action: Bracket}
  - { key: 07,       mods: Shift,         mode: Vi, action: FirstOccupied }
