#!/bin/sh

# Verbosity and settings that you pretty much just always are going to want
alias \
  exa="exa --group-directories-first" \
  cp="cp -iv" \
  mv="mv -iv" \
  rm="rm -v" \
  mkd="mkdir -pv" \
  yt="youtube-dl --add-metadata -i" \
  ytd="yt -x -f bestaudio/best" \
  ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
  diff="diff --color=auto"

# These common commands are just too long! Abbreviate them
alias \
  ytv="youtube-viewer" \
  xi="sudo xbps-install" \
  xr="sudo xbps-remove" \
  xq="xbps-query"

# Some other stuff
alias \
  vim="nvim" \
  vimdiff="nvim -d"
