#!/bin/sh
# This script is called by .xprofile on startup to remap keys.

# Increase key speed via a rate change
xset r rate 200 50
# Add english and russian layouts, toggle it with super+space, swap ctrl and caps
setxkbmap -layout us,ru -option grp:win_space_toggle,ctrl:swapcaps,altwin:swap_lalt_lwin
# Handle a short press of ctrl as esc
pkill xcape; xcape
