#!/bin/sh

alias \
  cddf="cd ~$DOTFILES" \
  cfa="$EDITOR ~$DOTFILES/aliasrc" \
  cfsc="$EDITOR ~$DOTFILES/shortcutrc" \
  cfzp="$EDITOR ~$DOTFILES/profile" \
  cfxp="$EDITOR ~$DOTFILES/xprofile" \
  cfi="$EDITOR ~$DOTFILES/i3config" \
  cfs="$EDITOR ~$DOTFILES/i3status.toml" \
  cfv="$EDITOR ~$DOTFILES/init.vim" \
  cfz="$EDITOR ~$DOTFILES/zshrc"
