icons = "awesome"

[theme]
name = "gruvbox-dark"

[theme.overrides]
separator = ""

[[block]]
block = "music"
player = "mpd"
max_width = 30
buttons = ["play"]

[[block]]
block = "sound"
step_width = 3

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "backlight"
device = "intel_backlight"

# [[block]]
# block = "pomodoro"
# length = 25
# break_length = 5
# message = "Take a break!"
# break_message = "Back to work!"

[[block]]
block = "networkmanager"

[[block]]
block = "time"
format = "%a %d/%m %R"
timezone = "Europe/Moscow"
interval = 60
