[icons]
icons = "awesome6"

[theme]
theme = "gruvbox-dark"
[theme.overrides]
separator = ""

[[block]]
block = "pomodoro"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "temperature"

[[block]]
block = "weather"
autolocate = true
autolocate_interval = "once"
[block.service]
name = "metno"

[[block]]
block = "net"
format = " $icon  $ssid $signal_strength $ip "
format_alt = " $icon ^icon_net_down $speed_down.eng(prefix:K) ^icon_net_up $speed_up.eng(prefix:K) "

[[block]]
block = "battery"
format = " $icon $percentage $time $power "

[[block]]
block = "time"
format = " $icon $timestamp.datetime(f:'%a %d/%m %R') "
