#!/bin/sh

# Verbosity and settings that you pretty much just always are going to want
alias \
  exa="exa --group-directories-first" \
  cp="cp -iv" \
  mv="mv -iv" \
  rm="rm -v" \
  mkd="mkdir -pv"

# Colorize commands when possible.
alias \
  diff="diff --color=auto"

# These common commands are just too long! Abbreviate them
alias \
  xi="sudo xbps-install" \
  xr="sudo xbps-remove -R" \
  xq="xbps-query"

# Some other stuff
alias vo="fd -t f | fzf | xargs vim"
