#!/usr/bin/env sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

remaps & # run the remaps script, switching caps/esc and more; check it for more info
dunst & # dunst for notifications
unclutter & # hide the mouse cursor if it isn't being used
mpd & # for music
